modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved, DragN0007"
issueTrackerURL="https://discord.gg/jubppqCzXj"
[[mods]]
modId="giddypigs"
version="${1.18.2-1.0}"
displayName="Giddy Guinea Pigs!"
logoFile="ggp_logo_big.png"
authors="DragN0007"
credits="Funder/ Commissioner, Beth"
description='''
Adds guinea pigs and decor!
'''
[[dependencies.giddypigs]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.giddypigs]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19.0)"
ordering="NONE"
side="BOTH"
[[dependencies.giddypigs]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering="NONE"
side="BOTH"
